export default {
  login: 'Login',
  register: 'Register',
  haveAccount: 'Already have an account? ',
  newAccount: 'New user? ',
  registerHere: 'Register here.',
  enterEmail: 'Enter email',
  enterPassword: 'Enter password',
  pleaseEnterEmail: 'Please enter email',
  pleaseEnterPassword: 'Please enter password',
  pleaseEnaterValidEmail: 'Please enter valid email',
  enterFirstName: 'Enter first name',
  pleaseEnterFirstName: 'Please enter first name',
  enterLastName: 'Enter last name',
  pleaseEnterLastName: 'Please enter last name',
  confirmPassword: 'Confirm password',
  passwordDoNotMatch: 'Password do not match',
  somethingWentWrong: 'Something went wrong',
  unableToGetUsersList: 'Unable to get users list',
  loginSuccess: 'Login successful',
  registrationSuccessful: 'Registration successful',
  userNotExist: 'User does not exist',
  wrongPassword: 'Wrong password! Try again',
  topHeadLines: 'Top Headlines',
  newsDetail: 'News Detail',
  logout: 'Logout'
}